# Generated by Django 4.1 on 2024-03-11 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GS', '0002_people_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='age',
            field=models.IntegerField(),
        ),
    ]
